# Generated by Django 3.2.7 on 2022-01-16 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_songdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbllisteninghistory',
            fields=[
                ('song_listened_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.TextField()),
                ('song_id', models.TextField()),
                ('listen_count', models.IntegerField()),
                ('title', models.TextField()),
                ('release', models.TextField()),
                ('artist_name', models.TextField()),
                ('year', models.TextField()),
                ('song', models.TextField()),
            ],
            options={
                'db_table': 'tbllisteninghistory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblsongslibrary',
            fields=[
                ('song_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('release', models.TextField()),
                ('artist_name', models.TextField()),
                ('year', models.TextField()),
            ],
            options={
                'db_table': 'tblsongslibrary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='default.jpeg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
